# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - DB=MYSQL CORE_RELEASE=3.6

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL PDO=1 CORE_RELEASE=3.2
    - php: 5.6
      env: DB=MYSQL PDO=1 CORE_RELEASE=3.3
    - php: 5.6
      env: DB=MYSQL PDO=1 CORE_RELEASE=3.4
    - php: 5.6
      env: DB=MYSQL PDO=1 CORE_RELEASE=3.5

before_install:
  - pip install --user codecov

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover sitetree-labels/tests

after_success:
    - mv coverage.clover ~/build/$TRAVIS_REPO_SLUG/
    - cd ~/build/$TRAVIS_REPO_SLUG

    # Upload Coverage to Scrutinizer
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

    # Upload test coverage to codecov
    - codecov
